### ISSUE TITLE
GeoLite2 support

### ISSUE THREAD

**Issue by megastef** [msimerson/maxmind-geolite-mirror#12]
Hi, 

we use the maxmind API and  maxmind-geolite-mirror to download the files. 
After changing to V1 API, we still get this error message in nodejs: 
```
Uncaught Error: Maxmind v1 module has changed API.
  Upgrade instructions can be found here:   https://github.com/runk/node-maxmind/wiki/Migration-guide
  If you want to use legacy libary then explicitly install maxmind@0.6

at new Metadata (node_modules/maxmind/lib/metadata.js:18:11)
      at Reader.load (node_modules/maxmind/lib/reader.js:27:19)
      at new Reader (node_modules/maxmind/lib/reader.js:21:8)
      at node_modules/maxmind/index.js:18:18

```

I assume the problem is the difference data format GeoLite & GeoLite2 and not the called API function. Please check https://github.com/runk/node-maxmind/wiki/Migration-guide for more information.

**Comment by megastef** [comment]
Sorry, found the problem - the file name changed to GeoLite2-City.mmdb
